import { NbMenuItem } from "@nebular/theme";
import { environment } from "../../../environments/environment";
import { MyCustomMenuItem } from "../../core/interfaces/menu-links.interface";

type userInfo = {
  name: string;
  email: string;
  role: string[];
};

// let token = sessionStorage.getItem('token');

function checkRoles(allowedRole: string): boolean {
  let userInfos: userInfo = JSON.parse(
    sessionStorage.getItem("user-profile") || "{}",
  );

  //if(userInfos.role.find(value => value == environment.allowedRoles.geral))
  //return true;

  if (userInfos.role.find((value) => value == allowedRole)) return true;

  return false;
}

// export const menulinks: MyCustomMenuItem[] = [
//   // SEÇÃO: ORÇAMENTO
//   {
//     title: "Orçamento",
//     id: 1,
//     name: "Planejamento Orçamentário",
//     icon: "logo-spo-branco.svg",
//     link: "/pages/planejamento-orcamentario",
//     status: true,
//     url: "",
//     src: "SPO",
//     menuIcon: "",
//     color: "#9780ad",
//     subTitle: "Sistema de Planejamento Orçamentário",
//     isExternal: false,
//     section: "orcamento",
//     separator: true,
//     sectionTitle: "Orçamento",
//   },
//   {
//     title: "Orçamento",
//     id: 2,
//     name: "Execução Orçamentária",
//     icon: "painelOrcamento.svg",
//     link: "/pages/execucao-orcamentaria",
//     status: checkRoles(environment.allowedRoles.execucaoOrcamentaria),
//     url: "",
//     src: "Sigefes",
//     menuIcon: "",
//     color: "#4DB6D2",
//     subTitle: "Execução Orçamentária",
//     isExternal: false,
//     section: "orcamento",
//   },
//   {
//     title: "Orçamento",
//     id: 3,
//     status: checkRoles(environment.allowedRoles.sas),
//     name: "Painéis SAS(Sigefes)",
//     link: "",
//     url: environment.urls.sas,
//     icon: "menu-icone-sas.svg",
//     src: "Sigefes/SAS Sefaz",
//     menuIcon: "",
//     color: "#0478ce",
//     isExternal: true,
//     subTitle: "Link externo para o Painéis SAS(Sigefes)",
//     section: "orcamento",
//   },
//   {
//     title: "Orçamento",
//     id: 4,
//     status: false,
//     name: "Gestão Fiscal",
//     icon: "menu-icone-gestao-fiscal.svg",
//     link: "/pages/gfiscal",
//     url: "",
//     src: "Sigefes/BI SEP",
//     menuIcon: "",
//     color: "red",
//     isExternal: false,
//     section: "orcamento",
//   },

//   // SEÇÃO: PROJETOS
//   {
//     title: "Projetos",
//     id: 5,
//     status: checkRoles(environment.allowedRoles.projetosEstrategicos),
//     name: "Projetos Estratégicos",
//     link: "/pages/strategicProjects",
//     url: "",
//     icon: "menu-icone-openpmo.svg",
//     src: "OpenPMO",
//     menuIcon: "",
//     color: "#44B39B",
//     subTitle: "Portfólio Realiza+",
//     isExternal: false,
//     section: "projetos",
//     separator: true,
//     sectionTitle: "Projetos",
//   },
//   {
//     title: "Projetos",
//     id: 6,
//     status: checkRoles(environment.allowedRoles.indicadores),
//     name: "Indicadores Estratégicos",
//     link: "",
//     url: environment.urls.indicadores,
//     icon: "menu-icone-indicadores.svg",
//     src: "Indicadores Admin",
//     menuIcon: "",
//     color: "#5e759f",
//     isExternal: true,
//     subTitle:
//       "Link externo para o Painel de Indicadores Estratégicos do Governo do Espírito Santo",
//     section: "projetos",
//   },

//   {
//     title: "Projetos",
//     id: 7,
//     status: true,
//     name: "Programa Estado Presente",
//     icon: "logoAmareloEstadoPresente.svg",
//     link: "",
//     url: environment.urls.estadoPresente,
//     src: "Programa Estado Presente",
//     menuIcon: "",
//     color: "#f7a600ff",
//     subTitle:
//       "Link externo para o mapa das principais entregas do Programa Estado Presente",
//     isExternal: true,
//     section: "projetos",
//   },

//   // SEÇÃO: CAPTAÇÃO
//   {
//     title: "Captação",
//     id: 8,
//     status: checkRoles(environment.allowedRoles.capitacao),
//     name: "Captação de Recursos",
//     icon: "menu-icone-siscap.svg",
//     link: "/pages/capitation",
//     url: "",
//     src: "Siscap",
//     menuIcon: "",
//     color: "#F09BBE",
//     isExternal: false,
//     subTitle: "Siscap - Sistema de Captação de Recursos",
//     section: "captacao",
//     separator: true,
//     sectionTitle: "Captação de Recursos",
//   },
// ];

export const menulinks: MyCustomMenuItem[] = [
  // SEPARADOR ORÇAMENTO
  {
    id: 100,
    separator: true,
    sectionTitle: "Orçamento",
    section: "orcamento",
    status: false,
    title: "", name: "", icon: "", link: "", url: "", src: "",
    menuIcon: "", color: "#9780ad", subTitle: "", isExternal: false,
  },
  {
    title: "Orçamento",
    id: 1,
    name: "Planejamento Orçamentário",
    icon: "logo-spo-branco.svg",
    link: "/pages/planejamento-orcamentario",
    status: true,
    url: "",
    src: "SPO",
    menuIcon: "",
    color: "#9780ad",
    subTitle: "Sistema de Planejamento Orçamentário",
    isExternal: false,
    section: "orcamento",
    separator: true,
    sectionTitle: "Orçamento",
  },
  {
    title: "Orçamento",
    id: 2,
    name: "Execução Orçamentária",
    icon: "painelOrcamento.svg",
    link: "/pages/execucao-orcamentaria",
    status: checkRoles(environment.allowedRoles.execucaoOrcamentaria),
    url: "",
    src: "Sigefes",
    menuIcon: "",
    color: "#4DB6D2",
    subTitle: "Execução Orçamentária",
    isExternal: false,
    section: "orcamento",
  },
  {
    title: "Orçamento",
    id: 3,
    status: checkRoles(environment.allowedRoles.sas),
    name: "Painéis SAS(Sigefes)",
    link: "",
    url: environment.urls.sas,
    icon: "menu-icone-sas.svg",
    src: "Sigefes/SAS Sefaz",
    menuIcon: "",
    color: "#0478ce",
    isExternal: true,
    subTitle: "Link externo para o Painéis SAS(Sigefes)",
    section: "orcamento",
  },
  {
    title: "Orçamento",
    id: 4,
    status: false,
    name: "Gestão Fiscal",
    icon: "menu-icone-gestao-fiscal.svg",
    link: "/pages/gfiscal",
    url: "",
    src: "Sigefes/BI SEP",
    menuIcon: "",
    color: "red",
    isExternal: false,
    section: "orcamento",
  },

  // SEPARADOR PROJETOS
  {
    id: 101,
    separator: true,
    sectionTitle: "Projetos",
    section: "projetos",
    status: false,
    title: "projetos", name: "", icon: "", link: "", url: "", src: "",
    menuIcon: "", color: "#44B39B", subTitle: "", isExternal: false,
  },
  {
    title: "Projetos",
    id: 5,
    status: checkRoles(environment.allowedRoles.projetosEstrategicos),
    name: "Projetos Estratégicos",
    link: "/pages/strategicProjects",
    url: "",
    icon: "menu-icone-openpmo.svg",
    src: "OpenPMO",
    menuIcon: "",
    color: "#44B39B",
    subTitle: "Portfólio Realiza+",
    isExternal: false,
    section: "projetos",
  },
  {
    title: "Projetos",
    id: 6,
    status: checkRoles(environment.allowedRoles.indicadores),
    name: "Indicadores Estratégicos",
    link: "",
    url: environment.urls.indicadores,
    icon: "menu-icone-indicadores.svg",
    src: "Indicadores Admin",
    menuIcon: "",
    color: "#5e759f",
    isExternal: true,
    subTitle: "Link externo para o Painel de Indicadores Estratégicos do Governo do Espírito Santo",
    section: "projetos",
  },
  {
    title: "Projetos",
    id: 7,
    status: true,
    name: "Programa Estado Presente",
    icon: "logoAmareloEstadoPresente.svg",
    link: "",
    url: environment.urls.estadoPresente,
    src: "Programa Estado Presente",
    menuIcon: "",
    color: "#f7a600ff",
    subTitle: "Link externo para o mapa das principais entregas do Programa Estado Presente",
    isExternal: true,
    section: "projetos",
  },

  // SEPARADOR CAPTAÇÃO
  {
    id: 102,
    separator: true,
    sectionTitle: "Captação de Recursos",
    section: "captacao",
    status: false,
    title: "", name: "", icon: "", link: "", url: "", src: "",
    menuIcon: "", color: "#F09BBE", subTitle: "", isExternal: false,
  },
  {
    title: "Captação",
    id: 8,
    status: checkRoles(environment.allowedRoles.capitacao),
    name: "Captação de Recursos",
    icon: "menu-icone-siscap.svg",
    link: "/pages/capitation",
    url: "",
    src: "Siscap",
    menuIcon: "",
    color: "#F09BBE",
    isExternal: false,
    subTitle: "Siscap - Sistema de Captação de Recursos",
    section: "captacao",
  },
];
